apps/frontend/lib/frontend_web/router.ex
defmodule FrontendWeb.Router do
  use FrontendWeb, :router

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_live_flash)
    plug(:put_root_layout, {FrontendWeb.LayoutView, :root})
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
    plug(FrontendWeb.Plugs.SetCurrentUser)
  end

  pipeline :ajax do
    plug(:accepts, ["json"])
    plug(:fetch_session)
    plug(:protect_from_forgery)
    plug(FrontendWeb.Plugs.SetCurrentUser)
  end

  pipeline :api do
    plug(:accepts, ["json"])
    plug(FrontendWeb.Plugs.BearerAuth)
  end

  scope "/", FrontendWeb do
    pipe_through(:browser)

    # Root
    get("/", PageController, :index)
    get("/help", PageController, :help)
    get("/terms", PageController, :terms)
    get("/privacy", PageController, :privacy)

    # Profile
    get("/profile", PageController, :profile)
    put("/profile", PageController, :update)

    # Item new
    live("/new", ItemLive, :new)
    live("/new/:chosen_type", ItemLive, :new_item)

    # Changes
    get("/feed", FeedController, :index)

    # Browse types
    live("/browse", BrowseLive, :index)
    live("/browse/:type", BrowseLive.Show, :show)
    live("/browse/:type/:menu", BrowseLive.Show, :show)

    # Item view
    live("/uid/:uid", ItemLive, :show)
    live("/uid/:uid/changes", ItemLive, :changes)
    live("/uid/:uid/edit", ItemLive, :edit)

    # Search
    live("/search", SearchLive, :index)

    # Query
    get("/query", QueryController, :index)
  end

  # Ajax
  scope "/ajax", FrontendWeb do
    pipe_through([:ajax])

    get("/relations", AjaxController, :relations)
    post("/relations", AjaxController, :relations)
    post("/save", AjaxController, :save)
  end

  scope "/auth", FrontendWeb do
    pipe_through([:browser])
    # should be #DELETE
    get("/logout", AuthController, :delete)
    get("/login", AuthController, :login)
    get("/signup", AuthController, :signup)
    post("/identity/callback", AuthController, :callback)
  end

  scope "/api", FrontendWeb do
    pipe_through(:api)

    post("/create", ApiController, :create)
    post("/update", ApiController, :update)
    get("/search", ApiController, :search)
    get("/query", ApiController, :query)
    get("/item/:id", ApiController, :show)
  end
end

apps/frontend/lib/frontend_web/live/item/_predicate.ex
defmodule FrontendWeb.ItemLive.Predicate do
  use FrontendWeb, :live_component

  def render(assigns) do
    cond do
      Map.get(assigns, :template, false) ->
        try do
          FrontendWeb.NewItemView.render(
            "#{assigns.folder}/predicate/#{assigns.template}.html",
            assigns
          )
        rescue
          e ->
            assigns
            |> Map.delete(:template)
            |> render()
        end

      Map.get(assigns, :type, false) ->
        try do
          FrontendWeb.NewItemView.render(
            "#{assigns.folder}/predicate/#{assigns.type}.html",
            assigns
          )
        rescue
          _ ->
            assigns
            |> Map.delete(:type)
            |> render()
        end

      true ->
        FrontendWeb.NewItemView.render(
          "#{assigns.folder}/predicate/_default.html",
          assigns
        )
    end
  end
end

apps/frontend/lib/frontend_web/templates/new_item/show/predicate/special/crew_film.html.leex
<div class="p-4 flex space-x-2">
  <%= live_redirect to: Routes.item_path(@socket, :show, @value.person.uid), replace: false, class: "px-3 py-1 mr-1 text-sm text-white bg-indigo-500 rounded-lg hover:bg-indigo-600" do %>
    <%= Map.get(get_lang(Map.get(@value.person, :label, []), "sv-SE"), :value, "Unknown") %>
  <% end %>
  <span><%= @value.job %></span>
</div>

apps/frontend/lib/frontend_web/templates/new_item/show/predicate/special/crew_person.html.leex
<div class="p-4 flex space-x-2">
  <%= live_redirect to: Routes.item_path(@socket, :show, @value.film.uid), replace: false, class: "px-3 py-1 mr-1 text-sm text-white bg-indigo-500 rounded-lg hover:bg-indigo-600" do %>
    <%= Map.get(get_lang(Map.get(@value.film, :label, []), "sv-SE"), :value, "Unknown") %>
  <% end %>
  <span><%= @value.job %></span>
</div>

apps/frontend/lib/frontend_web/templates/new_item/show/predicate/special/lang_string.html.leex
<div class="py-4 sm:py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
  <%= unless Map.get(assigns, :only_values, false), do: live_component(@socket, FrontendWeb.ItemLive.PredicateHeader, folder: "show", predicate: @predicate) %>
  <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
    <%= for lang <- @value do %>
      <%= live_component(@socket, FrontendWeb.ItemLive.Language, folder: "show", type: "string", value: lang) %>
    <% end %>
  </dd>
</div>

apps/frontend/lib/frontend_web/templates/new_item/show/predicate/special/lang_string_item.html.leex
<div class="flex">
  <div class="font-medium leading-snug w-1/3"><%= Graph.Struct.Language.find(:code, @value.language).name %></div>
  <div><%= @value.value %></div>
</div>

apps/frontend/lib/frontend_web/templates/new_item/show/predicate/special/lang_text.html.leex
<div class="py-4 sm:py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
  <%= unless Map.get(assigns, :only_values, false), do: live_component(@socket, FrontendWeb.ItemLive.PredicateHeader, folder: "show", predicate: @predicate) %>
  <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
    <%= for lang <- @value do %>
      <%= live_component(@socket, FrontendWeb.ItemLive.Language, folder: "show", type: "text", value: lang) %>
    <% end %>
  </dd>
</div>

apps/frontend/lib/frontend_web/templates/new_item/show/predicate/special/lang_text_item.html.leex
<div class="flex">
  <div class="font-medium leading-snug w-1/3"><%= Graph.Struct.Language.find(:code, @value.language).name %></div>
  <div><%= @value.value %></div>
</div>

apps/frontend/lib/frontend_web/templates/new_item/show/predicate/special/performance_film.html.leex
<div class="p-4">
  <%= live_redirect to: Routes.item_path(@socket, :show, @value.person.uid), replace: false, class: "px-3 py-1 mr-1 text-sm text-white bg-indigo-500 rounded-lg hover:bg-indigo-600" do %>
    <%= Map.get(get_lang(Map.get(@value.person, :label, []), "sv-SE"), :value, "Unknown") %>
  <% end %>
</div>

apps/frontend/lib/frontend_web/templates/new_item/show/predicate/special/performance_person.html.leex
<div class="p-4">
  <%= live_redirect to: Routes.item_path(@socket, :show, @value.film.uid), replace: false, class: "px-3 py-1 mr-1 text-sm text-white bg-indigo-500 rounded-lg hover:bg-indigo-600" do %>
    <%= Map.get(get_lang(Map.get(@value.film, :label, []), "sv-SE"), :value, "Unknown") %>
  <% end %>
</div>